POST  http://localhost:4000/wines/wines/rating/delete/623dd56dbadbfe57093a37a2
Content-Type: application/json

# {
#     "vzorka_id": "620d062219ae238bc93223e0",
#     "cirost": "kokotina",
#     "farba": "farba",
#     "intenzita": "intenzita",
#     "cistota": "cistota",
#     "harmonia": "harmonia",
#     "intenzitaChut": "intenzitaChut",
#     "cistotaChut": "cistotaChut",
#     "harmoniaChut": "harmoniaChut",
#     "perzistencia": "perzistencia",
#     "cirostNotes": "cirostNotes",
#     "farbaNotes": "farbaNotes",
#     "intenzitaNotes": "intenzitaNotes",
#     "cistotaNotes": "cistotaNotes",
#     "harmoniaNotes": "harmoniaNotes",
#     "intenzitaChutNotes": "intenzitaChutNotes",
#     "cistotaChutNotes": "cistotaChutNotes",
#     "harmoniaChutNotes": "harmoniaChutNotes",
#     "perzistenciaNotes": "perzistenciaNotes"
# }

# {
#     "komisia": "Komisia_Post",
#     "vzorka": "Vzorka1",
#     "rocnik": 10,
#     "kategoria": "Kategoria_Post",
#     "vystavovatel": "Vystavovatel_Post"
# }